#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ibus-libpinyin
Version  : 1.11.1
Release  : 6
URL      : https://sourceforge.net/projects/libpinyin/files/ibus-libpinyin/ibus-libpinyin-1.11.1.tar.gz
Source0  : https://sourceforge.net/projects/libpinyin/files/ibus-libpinyin/ibus-libpinyin-1.11.1.tar.gz
Summary  : Intelligent Pinyin engine based on libpinyin for IBus
Group    : Development/Tools
License  : GPL-2.0
Requires: ibus-libpinyin-data = %{version}-%{release}
Requires: ibus-libpinyin-libexec = %{version}-%{release}
Requires: ibus-libpinyin-license = %{version}-%{release}
Requires: ibus-libpinyin-locales = %{version}-%{release}
BuildRequires : gettext
BuildRequires : lua-dev
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(ibus-1.0)
BuildRequires : pkgconfig(libpinyin)
BuildRequires : pkgconfig(lua)
BuildRequires : pkgconfig(sqlite3)
BuildRequires : pygobject
BuildRequires : sed

%description
ibus-libpinyin
Intelligent Pinyin engine based on libpinyin for IBus
Description
It includes a Chinese Pinyin input method and a Chinese ZhuYin (Bopomofo) input method based on libpinyin for IBus.

%package data
Summary: data components for the ibus-libpinyin package.
Group: Data

%description data
data components for the ibus-libpinyin package.


%package libexec
Summary: libexec components for the ibus-libpinyin package.
Group: Default
Requires: ibus-libpinyin-license = %{version}-%{release}

%description libexec
libexec components for the ibus-libpinyin package.


%package license
Summary: license components for the ibus-libpinyin package.
Group: Default

%description license
license components for the ibus-libpinyin package.


%package locales
Summary: locales components for the ibus-libpinyin package.
Group: Default

%description locales
locales components for the ibus-libpinyin package.


%prep
%setup -q -n ibus-libpinyin-1.11.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1558339547
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static --disable-lua-extension
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1558339547
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ibus-libpinyin
cp COPYING %{buildroot}/usr/share/package-licenses/ibus-libpinyin/COPYING
%make_install
%find_lang ibus-libpinyin

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/appdata/libpinyin.appdata.xml
/usr/share/applications/ibus-setup-libbopomofo.desktop
/usr/share/applications/ibus-setup-libpinyin.desktop
/usr/share/glib-2.0/schemas/com.github.libpinyin.ibus-libpinyin.gschema.xml
/usr/share/ibus-libpinyin/db/english.db
/usr/share/ibus-libpinyin/db/strokes.db
/usr/share/ibus-libpinyin/icons/chinese.svg
/usr/share/ibus-libpinyin/icons/english.svg
/usr/share/ibus-libpinyin/icons/full-punct.svg
/usr/share/ibus-libpinyin/icons/full.svg
/usr/share/ibus-libpinyin/icons/half-punct.svg
/usr/share/ibus-libpinyin/icons/half.svg
/usr/share/ibus-libpinyin/icons/ibus-bopomofo.svg
/usr/share/ibus-libpinyin/icons/ibus-pinyin.svg
/usr/share/ibus-libpinyin/icons/simp-chinese.svg
/usr/share/ibus-libpinyin/icons/trad-chinese.svg
/usr/share/ibus-libpinyin/setup/config.py
/usr/share/ibus-libpinyin/setup/dicttreeview.py
/usr/share/ibus-libpinyin/setup/ibus-libpinyin-preferences.ui
/usr/share/ibus-libpinyin/setup/keyboardshortcut.py
/usr/share/ibus-libpinyin/setup/main2.py
/usr/share/ibus-libpinyin/setup/shortcuteditor.py
/usr/share/ibus/component/libpinyin.xml

%files libexec
%defattr(-,root,root,-)
/usr/libexec/ibus-engine-libpinyin
/usr/libexec/ibus-setup-libpinyin

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ibus-libpinyin/COPYING

%files locales -f ibus-libpinyin.lang
%defattr(-,root,root,-)

