#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ibus-libpinyin
Version  : 1.14.91
Release  : 19
URL      : https://sourceforge.net/projects/libpinyin/files/ibus-libpinyin/ibus-libpinyin-1.14.91.tar.gz
Source0  : https://sourceforge.net/projects/libpinyin/files/ibus-libpinyin/ibus-libpinyin-1.14.91.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
BuildRequires : gettext
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(ibus-1.0)
BuildRequires : pkgconfig(json-glib-1.0)
BuildRequires : pkgconfig(libpinyin)
BuildRequires : pkgconfig(libsoup-2.4)
BuildRequires : pkgconfig(sqlite3)
BuildRequires : sed

%description
ibus-libpinyin
Intelligent Pinyin engine based on libpinyin for IBus
Description
It includes a Chinese Pinyin input method and a Chinese ZhuYin (Bopomofo) input method based on libpinyin for IBus.

%prep
%setup -q -n ibus-libpinyin-1.14.91
cd %{_builddir}/ibus-libpinyin-1.14.91

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1666190150
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%configure --disable-static --disable-lua-extension
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1666190150
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ibus-libpinyin
cp %{_builddir}/ibus-libpinyin-%{version}/COPYING %{buildroot}/usr/share/package-licenses/ibus-libpinyin/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
%make_install

%files
%defattr(-,root,root,-)
